spring:
  application:
    name: vehicles
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
        
# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.zephyrover.vehicles: debug 
    root: info 